-- ============================================================
-- Migration 024_site_content.sql
--
-- Generic bilingual content-override table: instead of bespoke CMS
-- fields per page, this lets the admin override any of the app's
-- existing i18n keys (frontend/src/translations/index.js) by
-- content_key, per language. LanguageContext.jsx's t() checks this
-- table first and falls back to the hardcoded translation if no
-- override row (or no value for the current language) exists -- so
-- every existing t("...") call site across the whole app becomes
-- admin-editable with zero changes to those call sites, and nothing
-- breaks if a key has never been touched by an admin.
--
-- Seeded from the current fr/ar translation values themselves (263
-- string keys -- array-valued keys like home.whyItems are skipped,
-- they need a list editor, not a text field), so the admin's editor
-- starts fully populated with real content, not an empty form.
-- ============================================================
CREATE TABLE IF NOT EXISTS site_content (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  content_key   VARCHAR(150) NOT NULL UNIQUE,
  value_fr      TEXT NULL,
  value_ar      TEXT NULL,
  category      VARCHAR(50) NOT NULL,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_site_content_category (category)
);

INSERT INTO site_content (content_key, category, value_fr, value_ar) VALUES
  ('nav.links.home', 'nav', 'Accueil', 'الرئيسية'),
  ('nav.links.ourStory', 'nav', 'Notre Histoire', 'قصتنا'),
  ('nav.links.packs', 'nav', 'Packs', 'الباقات'),
  ('nav.links.createPack', 'nav', 'Créer Mon Pack', 'أنشئ باقتك'),
  ('nav.shopLabel', 'nav', 'Shop', 'تسوق'),
  ('nav.shopByGenre', 'nav', 'Shop par genre', 'التسوق حسب الجنس'),
  ('nav.viewAll', 'nav', 'Voir tout', 'عرض الكل'),
  ('nav.ourHistory', 'nav', 'Notre histoire', 'قصتنا'),
  ('nav.originals', 'nav', 'Catalogue', 'أوريجينالز'),
  ('nav.exclusif', 'nav', 'Exclusif', 'حصري'),
  ('nav.searchPlaceholder', 'nav', 'Rechercher…', 'بحث…'),
  ('nav.searchLabel', 'nav', 'Recherche', 'بحث'),
  ('nav.suggestions', 'nav', 'Suggestions', 'اقتراحات'),
  ('nav.results', 'nav', 'Résultats', 'النتائج'),
  ('nav.searching', 'nav', 'Recherche en cours…', 'جارٍ البحث…'),
  ('nav.noResults', 'nav', 'Aucun résultat pour', 'لا توجد نتائج لـ'),
  ('nav.viewAllResults', 'nav', 'Tous les résultats pour', 'جميع النتائج لـ'),
  ('nav.dashboard', 'nav', 'Dashboard', 'لوحة التحكم'),
  ('nav.logout', 'nav', 'Déco', 'خروج'),
  ('nav.disconnect', 'nav', 'Déconnexion', 'تسجيل الخروج'),
  ('nav.proSpace', 'nav', 'Espace Pro', 'المنطقة المهنية'),
  ('nav.admin', 'nav', 'Admin', 'مشرف'),
  ('nav.favorites', 'nav', 'Favoris', 'المفضلة'),
  ('nav.navigation', 'nav', 'Navigation', 'التنقل'),
  ('nav.perfumes', 'nav', 'Parfums', 'العطور'),
  ('nav.account', 'nav', 'Compte', 'الحساب'),
  ('nav.help', 'nav', 'Aide', 'المساعدة'),
  ('nav.delivery', 'nav', 'Livraison', 'التوصيل'),
  ('nav.faq', 'nav', 'FAQ', 'الأسئلة الشائعة'),
  ('nav.contact', 'nav', 'Contact', 'التواصل'),
  ('nav.exploreCollection', 'nav', 'Explorer la collection', 'استكشف المجموعة'),
  ('nav.searchPerfume', 'nav', 'Rechercher un parfum…', 'ابحث عن عطر…'),
  ('nav.legalNotice', 'nav', 'Mentions légales', 'الشروط القانونية'),
  ('nav.privacy', 'nav', 'Confidentialité', 'الخصوصية'),
  ('nav.terms', 'nav', 'CGV', 'الشروط العامة'),
  ('nav.language', 'nav', 'Langue', 'اللغة'),
  ('home.eyebrow', 'home', '✦ Packs de Parfums Curés', '✦ باقات عطور منتقاة بعناية'),
  ('home.title', 'home', 'Nos Packs de 4 Parfums', 'باقاتنا من 4 عطور'),
  ('home.subtitle', 'home', 'Chaque pack réunit 4 parfums pensés pour s''harmoniser. Prêt-à-offrir, personnalisable, ou entièrement sur-mesure.', 'كل باقة تجمع 4 عطور مصممة لتنسجم معاً. جاهزة للإهداء، قابلة للتخصيص، أو مصممة بالكامل حسب طلبك.'),
  ('home.viewAll', 'home', 'Voir tous les packs', 'عرض جميع الباقات'),
  ('home.comingSoon', 'home', 'Nos packs arrivent très bientôt. Revenez vite !', 'باقاتنا قادمة قريباً جداً. عودوا لزيارتنا!'),
  ('home.ctaTitle', 'home', 'Créez votre propre pack', 'أنشئ باقتك الخاصة'),
  ('home.ctaText', 'home', 'Choisissez exactement 4 parfums parmi toute notre collection. Votre pack, votre prix, votre style.', 'اختر بالضبط 4 عطور من مجموعتنا الكاملة. باقتك، سعرك، أسلوبك.'),
  ('home.ctaBtn', 'home', 'Commencer', 'ابدأ الآن'),
  ('home.whyEyebrow', 'home', '✦ Pourquoi Nahid', '✦ لماذا ناهد'),
  ('home.whyTitle', 'home', 'L''excellence, pack après pack', 'التميز، باقة تلو الأخرى'),
  ('home.ugcEyebrow', 'home', '✦ Nos clients', '✦ عملاؤنا'),
  ('home.ugcTitle', 'home', 'Ils ont reçu leur pack', 'استلموا باقتهم'),
  ('home.faqEyebrow', 'home', '✦ Questions', '✦ أسئلة'),
  ('home.faqTitle', 'home', 'Foire Aux Questions', 'الأسئلة الشائعة')
ON DUPLICATE KEY UPDATE content_key = content_key;

INSERT INTO site_content (content_key, category, value_fr, value_ar) VALUES
  ('home.newsletterTitle', 'home', 'Restez informé', 'ابقَ على اطلاع'),
  ('home.newsletterText', 'home', 'Recevez nos nouveaux packs et offres exclusives en avant-première.', 'احصل على باقاتنا الجديدة وعروضنا الحصرية أولاً بأول.'),
  ('home.newsletterPlaceholder', 'home', 'Votre email', 'بريدك الإلكتروني'),
  ('home.newsletterSuccessTitle', 'home', 'Merci !', 'شكراً لك!'),
  ('home.newsletterSuccessText', 'home', 'Vous êtes inscrit à notre newsletter.', 'تم تسجيلك في نشرتنا الإخبارية.'),
  ('home.addedToCart', 'home', 'Ajouté au panier', 'أُضيف إلى السلة'),
  ('directOrder.title', 'directOrder', 'Commandez en 2 minutes', 'اطلبي باك العطور ديالك الآن'),
  ('directOrder.subtitle', 'directOrder', 'Choisissez un pack, remplissez vos informations, c''est livré.', 'اختاري الباك المناسب لك وكمّلي الطلب مباشرة من الموقع'),
  ('directOrder.yourPack', 'directOrder', 'Votre pack', 'باقتك'),
  ('directOrder.choosePackLabel', 'directOrder', 'Choisir un pack', 'اختاري الباك'),
  ('directOrder.noPackPrompt', 'directOrder', 'Choisissez un pack ci-dessus pour commencer votre commande.', 'اختاري باقة من الأعلى لبدء طلبك.'),
  ('directOrder.formTitle', 'directOrder', 'Informations de livraison', 'معلومات التوصيل'),
  ('directOrder.quantityLabel', 'directOrder', 'Quantité', 'الكمية'),
  ('directOrder.cityPlaceholder', 'directOrder', 'Choisir une ville', 'اختاري المدينة'),
  ('directOrder.cityOther', 'directOrder', 'Autre ville', 'مدينة أخرى'),
  ('directOrder.cityOtherPlaceholder', 'directOrder', 'Précisez votre ville', 'حددي مدينتك'),
  ('directOrder.confirmBtn', 'directOrder', 'Je commande — Paiement à la livraison', 'اطلبي الآن — الدفع عند الاستلام'),
  ('directOrder.successTitle', 'directOrder', 'Commande enregistrée !', 'تم تسجيل طلبك بنجاح'),
  ('directOrder.successText', 'directOrder', 'Nous vous contacterons bientôt pour confirmer la livraison.', 'سنتواصل معك قريباً لتأكيد التوصيل.'),
  ('reviewsSection.eyebrow', 'reviewsSection', '✦ Témoignages', '✦ آراء عملائنا'),
  ('reviewsSection.title', 'reviewsSection', 'Ils ont trouvé leur signature', 'وجدوا توقيعهم العطري'),
  ('reviewsSection.reviewsWord', 'reviewsSection', 'avis', 'تقييم'),
  ('reviewsSection.ctaSub', 'reviewsSection', 'Vous avez essayé un de nos parfums ?', 'جربتي أحد عطورنا؟'),
  ('reviewsSection.ctaBtn', 'reviewsSection', 'Laisser mon avis', 'شاركينا رأيك'),
  ('packsPage.title', 'packsPage', 'Nos Packs', 'باقاتنا'),
  ('packsPage.subtitle', 'packsPage', 'Chaque pack réunit 4 parfums pensés pour s''harmoniser. Personnalisez-les à volonté ou créez le vôtre.', 'كل باقة تجمع 4 عطور مصممة لتنسجم معاً. خصصها بحرية أو أنشئ باقتك الخاصة.'),
  ('packsPage.searchPlaceholder', 'packsPage', 'Rechercher un pack...', 'ابحث عن باقة...'),
  ('packsPage.sortDefault', 'packsPage', 'Tri par défaut', 'الترتيب الافتراضي'),
  ('packsPage.sortPriceAsc', 'packsPage', 'Prix croissant', 'السعر تصاعدياً'),
  ('packsPage.sortPriceDesc', 'packsPage', 'Prix décroissant', 'السعر تنازلياً'),
  ('packsPage.empty', 'packsPage', 'Aucun pack ne correspond à votre recherche.', 'لا توجد باقة مطابقة لبحثك.'),
  ('packsPage.addedToCart', 'packsPage', 'Ajouté au panier', 'أُضيف إلى السلة'),
  ('packsPage.errorTitle', 'packsPage', 'Erreur', 'خطأ'),
  ('packsPage.errorText', 'packsPage', 'Impossible de charger les packs.', 'تعذر تحميل الباقات.'),
  ('packCard.details', 'packCard', 'Détails', 'التفاصيل'),
  ('packCard.addToCart', 'packCard', 'Ajouter', 'إضافة'),
  ('packCard.bestSeller', 'packCard', 'Best Seller', 'الأكثر مبيعاً'),
  ('packCard.new', 'packCard', 'Nouveau', 'جديد'),
  ('packCard.limited', 'packCard', 'Édition limitée', 'إصدار محدود'),
  ('packCard.customize', 'packCard', 'Personnaliser', 'تخصيص'),
  ('packCard.perfumesCount', 'packCard', 'parfums', 'عطور'),
  ('packCard.choosePack', 'packCard', 'Choisir ce pack', 'اختاري هذا الباك'),
  ('packCard.order', 'packCard', 'Commander', 'اطلبي الآن'),
  ('packCard.viewDetails', 'packCard', 'Détails du pack', 'تفاصيل الباك'),
  ('packDetails.back', 'packDetails', 'Retour aux packs', 'العودة إلى الباقات'),
  ('packDetails.addToCart', 'packDetails', 'Ajouter au panier', 'أضيفي للسلة'),
  ('packDetails.wishlist', 'packDetails', 'Favoris', 'المفضلة'),
  ('packDetails.share', 'packDetails', 'Partager', 'مشاركة'),
  ('packDetails.linkCopied', 'packDetails', 'Lien copié !', 'تم نسخ الرابط!'),
  ('packDetails.perfumesTitle', 'packDetails', 'Les 4 parfums de ce pack', 'العطور الأربعة في هذه الباقة')
ON DUPLICATE KEY UPDATE content_key = content_key;

INSERT INTO site_content (content_key, category, value_fr, value_ar) VALUES
  ('packDetails.containsFour', 'packDetails', 'Contient 4 parfums', 'تحتوي على 4 عطور'),
  ('packDetails.youSave', 'packDetails', 'Vous économisez', 'توفر'),
  ('packDetails.customizeToggle', 'packDetails', 'Personnaliser le pack', 'خصصي هذه الباقة'),
  ('packDetails.finishCustomize', 'packDetails', 'Terminer la personnalisation', 'إنهاء التخصيص'),
  ('packDetails.replace', 'packDetails', 'Remplacer', 'استبدال'),
  ('packDetails.changedTag', 'packDetails', 'Remplacé', 'تم الاستبدال'),
  ('packDetails.customizedSuffix', 'packDetails', '(personnalisé)', '(مخصصة)'),
  ('packDetails.customizedNote', 'packDetails', 'Pack personnalisé — le pack original n''est pas modifié.', 'باقة مخصصة — الباقة الأصلية لم تتغير.'),
  ('packDetails.customizedCta', 'packDetails', 'Ajouter la version personnalisée', 'أضف النسخة المخصصة'),
  ('packDetails.addedTitle', 'packDetails', 'Ajouté au panier !', 'أُضيف إلى السلة!'),
  ('packDetails.viewCartBtn', 'packDetails', 'Voir mon panier', 'عرض سلتي'),
  ('packDetails.continueBtn', 'packDetails', 'Continuer', 'متابعة'),
  ('packDetails.loading', 'packDetails', 'Chargement...', 'جارٍ التحميل...'),
  ('packDetails.notFound', 'packDetails', 'Pack introuvable', 'الباقة غير موجودة'),
  ('packDetails.errorTitle', 'packDetails', 'Erreur', 'خطأ'),
  ('packDetails.wishlistError', 'packDetails', 'Impossible de mettre à jour vos favoris.', 'تعذر تحديث المفضلة.'),
  ('replaceModal.title', 'replaceModal', 'Remplacer le parfum', 'استبدال هذا العطر'),
  ('replaceModal.close', 'replaceModal', 'Fermer', 'إغلاق'),
  ('replaceModal.currentLabel', 'replaceModal', 'Parfum actuel', 'العطر الحالي'),
  ('replaceModal.chooseNewLabel', 'replaceModal', 'Choisissez le nouveau parfum', 'اختر العطر الجديد'),
  ('replaceModal.searchPlaceholder', 'replaceModal', 'Rechercher un parfum...', 'ابحث عن عطر...'),
  ('replaceModal.empty', 'replaceModal', 'Aucun parfum trouvé', 'لم يتم العثور على أي عطر'),
  ('perfumeModal.close', 'perfumeModal', 'Fermer', 'إغلاق'),
  ('perfumeModal.size', 'perfumeModal', 'Taille', 'الحجم'),
  ('perfumeModal.concentration', 'perfumeModal', 'Concentration', 'التركيز'),
  ('perfumeModal.longevity', 'perfumeModal', 'Tenue', 'الثبات'),
  ('perfumeModal.scentFamily', 'perfumeModal', 'Famille olfactive', 'العائلة العطرية'),
  ('perfumeModal.inspiration', 'perfumeModal', 'Inspiration', 'مستوحى من'),
  ('perfumeModal.topNotes', 'perfumeModal', 'Tête', 'المقدمة'),
  ('perfumeModal.middleNotes', 'perfumeModal', 'Cœur', 'القلب'),
  ('perfumeModal.baseNotes', 'perfumeModal', 'Fond', 'القاعدة'),
  ('buildPack.title', 'buildPack', 'Créez Votre Propre Pack', 'أنشئ باقتك الخاصة'),
  ('buildPack.subtitle', 'buildPack', 'Choisissez exactement 4 parfums parmi notre collection et composez un pack unique, à votre image.', 'اختر بالضبط 4 عطور من مجموعتنا وكوّن باقة فريدة على طريقتك.'),
  ('buildPack.unavailableTitle', 'buildPack', 'Création de pack temporairement indisponible', 'إنشاء الباقات غير متاح مؤقتاً'),
  ('buildPack.unavailableText', 'buildPack', 'Revenez bientôt pour créer votre propre pack sur mesure.', 'عودوا قريباً لإنشاء باقتكم المخصصة.'),
  ('buildPack.selectedCount', 'buildPack', 'sélectionnés', 'محدد'),
  ('buildPack.searchPlaceholder', 'buildPack', 'Rechercher un parfum...', 'ابحث عن عطر...'),
  ('buildPack.allGenders', 'buildPack', 'Tous', 'الكل'),
  ('buildPack.view', 'buildPack', 'Voir', 'عرض'),
  ('buildPack.yourPack', 'buildPack', 'Votre pack', 'باقتك'),
  ('buildPack.chooseAPerfume', 'buildPack', 'Choisissez un parfum', 'اختر عطراً'),
  ('buildPack.priceLabel', 'buildPack', 'Prix du pack', 'سعر الباقة'),
  ('buildPack.addToCart', 'buildPack', 'Ajouter au panier', 'أضف إلى السلة'),
  ('buildPack.remaining', 'buildPack', 'Encore', 'تبقى'),
  ('buildPack.remainingSuffix', 'buildPack', 'parfum(s)', 'عطر(اً)'),
  ('buildPack.addedTitle', 'buildPack', 'Ajouté au panier !', 'أُضيف إلى السلة!'),
  ('buildPack.addedText', 'buildPack', 'Votre pack personnalisé a été ajouté.', 'تمت إضافة باقتك المخصصة.'),
  ('buildPack.continueBtn', 'buildPack', 'Continuer mes achats', 'متابعة التسوق'),
  ('buildPack.viewCartBtn', 'buildPack', 'Voir mon panier', 'عرض سلتي'),
  ('buildPack.loadError', 'buildPack', 'Impossible de charger les parfums.', 'تعذر تحميل العطور.')
ON DUPLICATE KEY UPDATE content_key = content_key;

INSERT INTO site_content (content_key, category, value_fr, value_ar) VALUES
  ('buildPack.errorTitle', 'buildPack', 'Erreur', 'خطأ'),
  ('buildPack.loading', 'buildPack', 'Chargement des parfums...', 'جارٍ تحميل العطور...'),
  ('buildPack.noMatch', 'buildPack', 'Aucun parfum ne correspond à votre recherche.', 'لا يوجد عطر يطابق بحثك.'),
  ('buildPack.defaultTitle', 'buildPack', 'Pack Personnalisé', 'باقة مخصصة'),
  ('buildPack.remove', 'buildPack', 'Retirer', 'إزالة'),
  ('cart.title', 'cart', 'Mon Panier', 'سلتي'),
  ('cart.emptyTitle', 'cart', 'Votre panier est vide', 'سلتك فارغة'),
  ('cart.emptyText', 'cart', 'Découvrez nos packs de parfums curés avec soin.', 'اكتشف باقات عطورنا المنتقاة بعناية.'),
  ('cart.exploreBtn', 'cart', 'Explorer les packs', 'استكشف الباقات'),
  ('cart.typeReadyPack', 'cart', 'Pack prêt', 'باقة جاهزة'),
  ('cart.typeCustomized', 'cart', 'Pack personnalisé', 'باقة مخصصة'),
  ('cart.typeCustom', 'cart', 'Pack sur-mesure', 'باقة حسب الطلب'),
  ('cart.summaryTitle', 'cart', 'Résumé', 'الملخص'),
  ('cart.subtotal', 'cart', 'Sous-total', 'المجموع الفرعي'),
  ('cart.shipping', 'cart', 'Livraison', 'التوصيل'),
  ('cart.free', 'cart', 'Gratuite', 'مجاني'),
  ('cart.discount', 'cart', 'Réduction', 'الخصم'),
  ('cart.couponPlaceholder', 'cart', 'Code promo', 'رمز الخصم'),
  ('cart.couponSuccessTitle', 'cart', 'Coupon appliqué !', 'تم تطبيق الرمز!'),
  ('cart.couponErrorTitle', 'cart', 'Coupon invalide', 'رمز غير صالح'),
  ('cart.couponErrorText', 'cart', 'Ce code n''est pas valide.', 'هذا الرمز غير صالح.'),
  ('cart.total', 'cart', 'Total', 'المجموع'),
  ('cart.checkoutBtn', 'cart', 'Passer commande', 'إتمام الطلب'),
  ('cart.remove', 'cart', 'Retirer', 'إزالة'),
  ('checkout.title', 'checkout', 'Finaliser ma commande', 'إتمام طلبي'),
  ('checkout.deliveryTitle', 'checkout', 'Informations de livraison', 'معلومات التوصيل'),
  ('checkout.fullName', 'checkout', 'Nom complet', 'الاسم الكامل'),
  ('checkout.fullNameError', 'checkout', 'Le nom est requis', 'الاسم مطلوب'),
  ('checkout.phone', 'checkout', 'Téléphone', 'رقم الهاتف'),
  ('checkout.phonePlaceholder', 'checkout', '06 12 34 56 78', '06 12 34 56 78'),
  ('checkout.phoneError', 'checkout', 'Numéro marocain invalide (ex: 06 12 34 56 78)', 'رقم هاتف مغربي غير صالح (مثال: 06 12 34 56 78)'),
  ('checkout.city', 'checkout', 'Ville', 'المدينة'),
  ('checkout.cityError', 'checkout', 'La ville est requise', 'المدينة مطلوبة'),
  ('checkout.address', 'checkout', 'Adresse complète', 'العنوان الكامل'),
  ('checkout.addressError', 'checkout', 'L''adresse est requise', 'العنوان مطلوب'),
  ('checkout.note', 'checkout', 'Note (optionnel)', 'ملاحظة (اختياري)'),
  ('checkout.notePlaceholder', 'checkout', 'Instructions de livraison, etc.', 'تعليمات التوصيل، إلخ.'),
  ('checkout.trustSecure', 'checkout', 'Paiement sécurisé', 'دفع آمن'),
  ('checkout.trustDelivery', 'checkout', 'Livraison partout au Maroc', 'توصيل في جميع أنحاء المغرب'),
  ('checkout.trustRefund', 'checkout', 'Satisfait ou remboursé', 'رضا تام أو استرجاع'),
  ('checkout.paymentTitle', 'checkout', 'Paiement', 'الدفع'),
  ('checkout.codTitle', 'checkout', 'Paiement à la livraison', 'الدفع عند الاستلام'),
  ('checkout.codText', 'checkout', 'Payez en espèces à la réception. Zéro risque, zéro prépaiement.', 'ادفع نقداً عند الاستلام. بدون أي مخاطرة، بدون دفع مسبق.'),
  ('checkout.summaryTitle', 'checkout', 'Résumé de commande', 'ملخص الطلب'),
  ('checkout.subtotal', 'checkout', 'Sous-total', 'المجموع الفرعي'),
  ('checkout.shipping', 'checkout', 'Livraison', 'التوصيل'),
  ('checkout.total', 'checkout', 'Total', 'المجموع'),
  ('checkout.submitBtn', 'checkout', 'Confirmer la commande', 'تأكيد الطلب'),
  ('checkout.submitting', 'checkout', 'Envoi en cours...', 'جارٍ الإرسال...'),
  ('checkout.errorTitle', 'checkout', 'Erreur lors de la commande', 'خطأ أثناء الطلب')
ON DUPLICATE KEY UPDATE content_key = content_key;

INSERT INTO site_content (content_key, category, value_fr, value_ar) VALUES
  ('checkout.errorRetry', 'checkout', 'Veuillez réessayer.', 'يرجى المحاولة مرة أخرى.'),
  ('checkout.emptyCartTitle', 'checkout', 'Votre panier est vide', 'سلتك فارغة'),
  ('checkout.exploreBtn', 'checkout', 'Explorer les packs', 'استكشف الباقات'),
  ('thankYou.title', 'thankYou', 'Merci pour votre commande !', 'مبروك! تم تسجيل طلبك بنجاح 🎉'),
  ('thankYou.subtitle', 'thankYou', 'Votre commande a bien été reçue et sera traitée sous peu.', 'تم استلام طلبك وسيتم التواصل معك قريباً لتأكيد التوصيل.'),
  ('thankYou.totalLabel', 'thankYou', 'Total', 'المجموع'),
  ('thankYou.codLabel', 'thankYou', 'Paiement à la livraison', 'الدفع عند الاستلام'),
  ('thankYou.upsellSectionTitle', 'thankYou', '🎁 Offre spéciale pour nos nouveaux clients', '🎁 عرض خاص لزبنائنا الجدد'),
  ('thankYou.upsellSectionSubtitle', 'thankYou', 'Offre spéciale : votre 2ème pack à seulement 150 DH', 'عرض خاص: الباقة الثانية بـ 150 درهم فقط'),
  ('thankYou.upsellBadge', 'thankYou', 'Offre spéciale', 'عرض خاص'),
  ('thankYou.upsellFreeDelivery', 'thankYou', 'Livraison incluse', 'التوصيل مشمول'),
  ('thankYou.upsellDecline', 'thankYou', 'Non merci, je garde ma commande telle quelle', 'لا شكراً، أكتفي بطلبـي'),
  ('thankYou.upsellAccept', 'thankYou', 'Ajouter ce pack pour', 'أضيفي هذا الباك بـ'),
  ('thankYou.upsellAdding', 'thankYou', 'Ajout...', 'جارٍ الإضافة...'),
  ('thankYou.upsellSuccessTitle', 'thankYou', 'Pack ajouté à votre commande !', 'تمت إضافة الباقة إلى طلبك!'),
  ('thankYou.upsellErrorTitle', 'thankYou', 'Erreur', 'خطأ'),
  ('thankYou.upsellErrorText', 'thankYou', 'Impossible d''ajouter ce pack.', 'تعذر إضافة هذه الباقة.'),
  ('thankYou.continueBtn', 'thankYou', 'Continuer mes achats', 'متابعة التسوق'),
  ('contactPage.title', 'contactPage', 'Contactez-nous', 'تواصل معنا'),
  ('contactPage.subtitle', 'contactPage', 'Une question sur un pack ou votre commande ? Notre équipe vous répond rapidement.', 'لديك سؤال حول باقة أو طلبك؟ فريقنا يرد بسرعة.'),
  ('contactPage.phoneLabel', 'contactPage', 'Téléphone', 'الهاتف'),
  ('contactPage.emailLabel', 'contactPage', 'Email', 'البريد الإلكتروني'),
  ('contactPage.deliveryLabel', 'contactPage', 'Livraison', 'التوصيل'),
  ('contactPage.deliveryValue', 'contactPage', 'Partout au Maroc · Paiement à la livraison', 'في جميع أنحاء المغرب · الدفع عند الاستلام'),
  ('contactPage.fullName', 'contactPage', 'Nom complet', 'الاسم الكامل'),
  ('contactPage.phone', 'contactPage', 'Téléphone', 'الهاتف'),
  ('contactPage.email', 'contactPage', 'Email', 'البريد الإلكتروني'),
  ('contactPage.subject', 'contactPage', 'Sujet', 'الموضوع'),
  ('contactPage.message', 'contactPage', 'Message', 'الرسالة'),
  ('contactPage.submitBtn', 'contactPage', 'Envoyer le message', 'إرسال الرسالة'),
  ('contactPage.sending', 'contactPage', 'Envoi...', 'جارٍ الإرسال...'),
  ('contactPage.successTitle', 'contactPage', 'Message envoyé !', 'تم إرسال الرسالة!'),
  ('contactPage.successText', 'contactPage', 'Nous vous répondrons très vite.', 'سنرد عليك في أقرب وقت.'),
  ('contactPage.errorTitle', 'contactPage', 'Erreur', 'خطأ'),
  ('contactPage.errorRetry', 'contactPage', 'Veuillez réessayer.', 'يرجى المحاولة مرة أخرى.'),
  ('faqPage.title', 'faqPage', 'Questions Fréquentes', 'الأسئلة الشائعة'),
  ('faqPage.subtitle', 'faqPage', 'Tout ce qu''il faut savoir sur nos packs de parfums.', 'كل ما تحتاج معرفته عن باقات عطورنا.'),
  ('faqPage.empty', 'faqPage', 'Aucune question pour le moment.', 'لا توجد أسئلة بعد.'),
  ('orderTrackingPage.title', 'orderTrackingPage', 'Suivre ma commande', 'تتبع طلبي'),
  ('orderTrackingPage.subtitle', 'orderTrackingPage', 'Entrez votre numéro de commande et votre téléphone pour suivre son avancement.', 'أدخل رقم طلبك ورقم هاتفك لتتبع حالته.'),
  ('orderTrackingPage.orderNumberPlaceholder', 'orderTrackingPage', 'Numéro de commande (ex: NHD-000123)', 'رقم الطلب (مثال: NHD-000123)'),
  ('orderTrackingPage.phonePlaceholder', 'orderTrackingPage', 'Téléphone', 'الهاتف'),
  ('orderTrackingPage.submitBtn', 'orderTrackingPage', 'Suivre', 'تتبع'),
  ('orderTrackingPage.searching', 'orderTrackingPage', 'Recherche...', 'جارٍ البحث...'),
  ('orderTrackingPage.notFound', 'orderTrackingPage', 'Commande introuvable. Vérifiez le numéro et le téléphone.', 'الطلب غير موجود. تحقق من الرقم والهاتف.'),
  ('orderTrackingPage.cancelled', 'orderTrackingPage', 'Cette commande a été annulée.', 'تم إلغاء هذا الطلب.'),
  ('orderTrackingPage.steps.pending', 'orderTrackingPage', 'Reçue', 'تم الاستلام'),
  ('orderTrackingPage.steps.confirmed', 'orderTrackingPage', 'Confirmée', 'تم التأكيد'),
  ('orderTrackingPage.steps.preparing', 'orderTrackingPage', 'Préparation', 'قيد التحضير'),
  ('orderTrackingPage.steps.shipping', 'orderTrackingPage', 'Expédition', 'قيد الشحن')
ON DUPLICATE KEY UPDATE content_key = content_key;

INSERT INTO site_content (content_key, category, value_fr, value_ar) VALUES
  ('orderTrackingPage.steps.delivered', 'orderTrackingPage', 'Livrée', 'تم التسليم'),
  ('wishlistPage.title', 'wishlistPage', 'Mes Favoris', 'مفضلتي'),
  ('wishlistPage.subtitle', 'wishlistPage', 'Retrouvez les parfums et packs que vous avez aimés.', 'اعثر على العطور والباقات التي أعجبتك.'),
  ('wishlistPage.loading', 'wishlistPage', 'Chargement...', 'جارٍ التحميل...'),
  ('wishlistPage.emptyTitle', 'wishlistPage', 'Aucun favori pour le moment', 'لا توجد عناصر مفضلة بعد'),
  ('wishlistPage.exploreBtn', 'wishlistPage', 'Découvrir nos packs', 'اكتشف باقاتنا'),
  ('wishlistPage.packsTitle', 'wishlistPage', 'Packs favoris', 'الباقات المفضلة'),
  ('wishlistPage.perfumesTitle', 'wishlistPage', 'Parfums favoris', 'العطور المفضلة'),
  ('wishlistPage.perfumesNote', 'wishlistPage', 'Ces parfums ne sont disponibles qu''au sein de nos packs.', 'هذه العطور متاحة فقط ضمن باقاتنا.'),
  ('wishlistPage.addToCart', 'wishlistPage', 'Ajouter', 'إضافة'),
  ('wishlistPage.addedToCart', 'wishlistPage', 'Ajouté au panier', 'أُضيف إلى السلة'),
  ('countdown.defaultLabel', 'countdown', 'Offre spéciale se termine dans', 'ينتهي العرض الخاص خلال'),
  ('whatsapp.tooltip', 'whatsapp', 'Contactez-nous sur WhatsApp', 'تواصل معنا عبر واتساب')
ON DUPLICATE KEY UPDATE content_key = content_key;
INSERT INTO schema_migrations (filename)
SELECT '024_site_content.sql' WHERE NOT EXISTS (SELECT 1 FROM schema_migrations WHERE filename = '024_site_content.sql');
